apiVersion: v1
kind: ServiceAccount
metadata:
  name: remote-cluster-provisioner
  namespace: remote-cluster-provisioner-system
  labels:
    app.kubernetes.io/name: remote-cluster-provisioner
    control-plane: controller-manager
