apiVersion: infra.dcn.ssu.ac.kr/v1
kind: RemoteCluster
metadata:
  name: remotecluster-sample
  namespace: default
  labels:
    app.kubernetes.io/name: remote-cluster-provisioner
    app.kubernetes.io/managed-by: kustomize

spec:
  # This must be unique for each cluster.
  # Used as:
  # 1. Kubernetes cluster name during provisioning
  # 2. Parent cluster name when adding worker nodes
  clusterName: "remotecluster-new"

  # Target node SSH information
  host: "192.168.3.234"
  port: 22
  user: "ubuntu"

  # Node information
  nodeInfo:
    # control-plane or worker
    nodeType: "control-plane"

    # cpu or gpu
    hardwareType: "cpu"

    softwareConfig:
      # GPU-related fields are optional.
      # Only required when hardwareType=gpu

      nvidiaDriverVersion: "580" #nvidia driver version for gpu node, e.g. 535.104.05
      nvidiaContainerToolkitVersion: "1.19.0-1" #nvidia container toolkit version for gpu node
      k8sDevicePluginVersion: "v0.17.1"
      kubernetesVersion: "v1.34.2"
      imagePrepulls:
        - "docker.io/vitu1/kernel-pytorch-gpu:3.2.3-cu121"
        - "docker.io/vitu1/kernel-tf-gpu:3.2.3-cu121"
      imagePullSecretRef:
        name: dockerhub-creds

  # VPN configuration
  vpnConfig:
    # VPN IP assigned to this node
    ip: "10.9.0.13"

    # Public IP of VPN server
    vpnServerPublicIP: "13.215.206.108"

    vpnSshCredentialsRef:
      name: "vpn-server-secret"
      namespace: "default"
      key: "id_rsa"

  # SSH authentication
  auth:
    sshPrivateKeySecretRef:
      name: "remote-cluster-new-secret"
      key: "password"

  # GitOps configuration
  gitConfig:
    # "true" or "false"
    enable: "true"

    # Git server URL
    gitServer: "http://192.168.3.99:31810"

    # Git username
    gitUsername: "nephio"

    # Upstream platform repository
    upstreamPlatformRepo: "catalog-workloads-mlplatform"

    # Branch/tag/commit
    packageRevision: "v1.0.0"

---
apiVersion: v1
kind: Secret
metadata:
  name: remote-cluster-new-secret
  namespace: default
type: Opaque
stringData:
  password: "1"

---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vpn-server-secret
#   namespace: default
# type: Opaque
# stringData:
#   password: "vpn-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: vpn-server-secret
  namespace: default
type: Opaque
stringData:
  id_rsa: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEA6Kb5qGDJAPDt60rm8JhR4RpzlS9rwaz74ACSjjBRz7uCKvr0
    jw05oU/cfvEekc7+PjX3O90kAe6EhI3m56WWABoxvXrbyII4MyTIkPKcMBENC0L2
    9JjZAP+Auo8EGriL2Kpz5DmGzqr/9uRMIjH5a87WCBJ3sxNrKW148b+8ZVO052bS
    W+VAwH26iq0h31TAHZl8R4jxDMkGH1mbaLP5Q156A29NqPYPW4xh0NCfj3Vpzp4S
    IcfnJv59rFuA8fBYn1XhtKDvIrQKSTI6igizC/H1/9kXph2fFSmHlvpaRU5HVUQx
    6naU2QNVfQ2r2gGEeLhidktFmJE3oA+YJ2lGpQIDAQABAoIBAA8byNrGbkdBXjIJ
    izXUrnyP2zG1AqpxMWo6n0ncmXOEGc/wvDEOCtAO/6K+xd1yM9CWcJfSpKP7eV+i
    V3xzpGodSV2kvOEok72+hcfj+YClmtNAZgk8Y9tMvG9hGkMh+PL5Hs2Tbs29DSJb
    cRZHaIs3w26CxIM8n5jxIwmQCgwKY+ISP9t6l/0axOOPwECpgOCQ3yWFeikmVKNe
    xA/N894Ru/yG0JdJMIbcQJAUd7v53jZI/F2F7QvTLBJtM5zBoH1ycnidGGzPagIn
    +WaRXxuEe2ZbHUu+EuOYLQSzo6OZKj+OV+CRMFs4sgyG7eYs1QO1TmwM1b6AfhTG
    TJ11pAECgYEA9sYK7Qo8Hx2DcxvclB+cy+4HlaH8w4ne7RMBOPCTnsVI50tExmTE
    uVlqtkKaifE0Ken1b/pYX/y3mt2SibbZFBOPh8B4goJMICVP6fCZnfY3dzFNIGK3
    Wma5EMHKYWGnf7Np1HkXqPQ77ESnC/ww1jIDQW6PLSDqBambaEssAE0CgYEA8VnF
    pPlz/ZCGq5+eR3fp6AgBjq7kvP4SpuabTlg+7frcL7I5I0pXXL3+k7dKyY+48AEZ
    E1ORifJxuCAIHw2K7A9yoIGoXKHb9KHXCIGwL0HIg+3qD9+WeI0NTKy6DpbZ6rd4
    twMcdbvQPKKwGkQlqW6B/k1QMrub2hEjQuHgy7kCgYBOkLSvzP9hJKNSBX/PhNUF
    tA2kHQN9OarIrbFI8Ib/GG5ifPszcqeTHx2zUzciTbG+2maytPBn9ux5mKtrvtQT
    6TpcDPIREuyrm1V69Ifj25zDDOYyNluLo4KuDBSjtlR+ep9p7veSadeeHClWzn65
    4whYT5uz0XPQQ7RfmvcyTQKBgAa+MlZsnb/81LZgzERE5mUULC73Ve6tzomZMceb
    kY6GjrZKbWw9/Hjb2gv4d/9vo4QZE8FFeXB4NJMnWfK8JyB3QgWX+cM0xndsOhzD
    us9nMBn3gK2W2pZdonx86unTbx0uqRG75YSojaXUCcWCF+dG7hzTviTctvr9tZV9
    yBEJAoGAFjw2ZLLaeE2QgOweFpqncEC5/qinpFc51dX8qTMfgNzDxb8EUOTfklBV
    hTpDPqU5c3ttLkACemOfp9eGUsIXPgCTYrDPzpKk6IIY+QLF8T7ANr1/zyju8SRK
    jtiM9JLrHsl6kUYB/3G4lUPo6hTcsavKTr1t4FeS1rcOfzswc1I=
    -----END RSA PRIVATE KEY-----
---
# Secret
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-creds
  namespace: default
type: Opaque
stringData:
  username: vitu1
  password: "REDACTED"