apiVersion: infra.dcn.ssu.ac.kr/v1
kind: RemoteCluster
metadata:
  labels:
    app.kubernetes.io/name: remote-cluster-provisioner
    app.kubernetes.io/managed-by: kustomize
  name: remotecluster-subnet30
spec:
  clusterName: "remotecluster-subnet30"
  host: "192.168.30.87"
  port: 22
  user: "ubuntu"

  auth:
    passwordSecretRef:
      name: remote-cluster-subnet30-secret
      key: password

  kubernetes:
    version: "v1.34.2"
  gitConfig:
    enable: "true"
    gitServer: "http://192.168.40.111:31810"
    gitUsername: "nephio"
    upstreamPlatformRepo: "catalog-workloads-mlplatform"
    packageRevision: "v1.0.0"
---
apiVersion: v1
kind: Secret
metadata:
  name: remote-cluster-subnet30-secret
  namespace: default
type: Opaque
stringData:
  password: "ckddmlrhks401!"
