apiVersion: infra.dcn.ssu.ac.kr/v1
kind: RemoteCluster
metadata:
  labels:
    app.kubernetes.io/name: remote-cluster-provisioner
    app.kubernetes.io/managed-by: kustomize
  name: remotecluster-sample
spec:
#This is for nodes with provided by user by IP address, if control-plane node, it will be used for cluster provisioning, if worker node, it will be added to the cluster after provisioning.
  clusterName: "remotecluster-new" ## this has to be unique for each cluster, and will be used as the cluster name when provisioning, and also will be used as the parent cluster name when adding worker node to the cluster.
  host: "192.168.3.234"
  port: 22
  user: "ubuntu"
  nodeInfo:
    nodeType: "control-plane" #control-plane or worker
    hardwareType: "cpu" #cpu or gpu

  auth:
    passwordSecretRef:
      name: remote-cluster-new-secret
      key: password

  kubernetes:
    version: "v1.34.2"
  gitConfig:
    enable: "true"
    gitServer: "http://192.168.3.99:31810"
    gitUsername: "nephio"
    upstreamPlatformRepo: "catalog-workloads-mlplatform"
    packageRevision: "v1.0.0"
---
apiVersion: v1
kind: Secret
metadata:
  name: remote-cluster-new-secret
  namespace: default
type: Opaque
stringData:
  password: "1"
