apiVersion: infra.dcn.ssu.ac.kr/v1
kind: RemoteCluster
metadata:
  name: remotecluster-sample
  namespace: default
  labels:
    app.kubernetes.io/name: remote-cluster-provisioner
    app.kubernetes.io/managed-by: kustomize

spec:
  # This must be unique for each cluster.
  # Used as:
  # 1. Kubernetes cluster name during provisioning
  # 2. Parent cluster name when adding worker nodes
  clusterName: "remotecluster-new"

  # Target node SSH information
  host: "192.168.3.234"
  port: 22
  user: "ubuntu"

  # Node information
  nodeInfo:
    # control-plane or worker
    nodeType: "control-plane"

    # cpu or gpu
    hardwareType: "cpu"

    softwareConfig:
      # GPU-related fields are optional.
      # Only required when hardwareType=gpu

      nvidiaDriverVersion: "580" #nvidia driver version for gpu node, e.g. 535.104.05
      nvidiaContainerToolkitVersion: "1.19.0-1" #nvidia container toolkit version for gpu node
      k8sDevicePluginVersion: "v0.17.1"
      kubernetesVersion: "v1.34.2"
      imagePrepulls:
        - "docker.io/vitu1/kernel-pytorch-gpu:3.2.3-cu121"
        - "docker.io/vitu1/kernel-tf-gpu:3.2.3-cu121"
      imagePullSecretRef:
        name: dockerhub-creds

  # VPN configuration
  vpnConfig:
    # VPN IP assigned to this node
    ip: "10.9.0.13"

    # Public IP of VPN server
    vpnServerPublicIP: "13.215.206.108"

    vpnSshCredentialsRef:
      name: "vpn-server-secret"
      namespace: "default"
      key: "id_rsa"

  # SSH authentication
  auth:
    sshPrivateKeySecretRef:
      name: "remote-cluster-new-secret"
      key: "password"

  # GitOps configuration
  gitConfig:
    # "true" or "false"
    enable: "true"

    # Git server URL
    gitServer: "http://192.168.3.99:31810"

    # Git username
    gitUsername: "nephio"

    # Upstream platform repository
    upstreamPlatformRepo: "catalog-workloads-mlplatform"

    # Branch/tag/commit
    packageRevision: "v1.0.0"

---
apiVersion: v1
kind: Secret
metadata:
  name: remote-cluster-new-secret
  namespace: default
type: Opaque
stringData:
  password: "1"

---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vpn-server-secret
#   namespace: default
# type: Opaque
# stringData:
#   password: "vpn-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: vpn-server-secret
  namespace: default
type: Opaque
stringData:
  id_rsa: |
    -----BEGIN RSA PRIVATE KEY-----
    CHANGE ME TO YOUR VPN SERVER PRIVATE KEY
    -----END RSA PRIVATE KEY-----
---
# Secret
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-creds
  namespace: default
type: Opaque
stringData:
  username: vitu1
  password: changeme