// Package awsnodeprovision implements AWS EC2 node provisioning for the
// NodeProvision controller.  It follows the same VPN-centric architecture as
// the on-prem provisioner: a WireGuard keypair is generated by the controller,
// the peer is registered on the VPN server via SSH, and the WireGuard client
// config plus the kubeadm join command are embedded in a cloud-init user-data
// script that runs automatically when the EC2 instance first boots.
package awsnodeprovision

import (
	"context"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"log"
	"sort"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/ec2"
	"github.com/aws/aws-sdk-go-v2/service/ec2/types"
	"golang.org/x/crypto/ssh"

	mlv1alpha1 "dcn.ssu.ac.kr/infra/api/ml/v1alpha1"
	remotenodeprovision "dcn.ssu.ac.kr/infra/helpers/remote-node-provision"
	sshhelper "dcn.ssu.ac.kr/infra/helpers/ssh"
	corev1 "k8s.io/api/core/v1"
)

// AWSCredentials holds static AWS credentials resolved from a Kubernetes Secret.
// If both fields are empty the SDK falls back to its default credential chain
// (environment variables, instance profile, ~/.aws/credentials).
type AWSCredentials struct {
	AccessKeyID     string
	SecretAccessKey string
	SessionToken    string
}

// newEC2Client builds an EC2 client for the given region.  When creds fields
// are empty the SDK's default credential provider chain is used (IAM role).
func newEC2Client(ctx context.Context, region string, creds AWSCredentials) (*ec2.Client, error) {
	var opts []func(*config.LoadOptions) error
	opts = append(opts, config.WithRegion(region))

	if creds.AccessKeyID != "" && creds.SecretAccessKey != "" {
		opts = append(opts, config.WithCredentialsProvider(
			credentials.NewStaticCredentialsProvider(
				creds.AccessKeyID,
				creds.SecretAccessKey,
				creds.SessionToken,
			),
		))
	}

	cfg, err := config.LoadDefaultConfig(ctx, opts...)
	if err != nil {
		return nil, fmt.Errorf("loading AWS config: %w", err)
	}
	return ec2.NewFromConfig(cfg), nil
}

// ResolveAWSCredentials extracts AWS static credentials from a secret.
// If the secret does not contain the expected keys the returned struct is
// zero-valued and the SDK will use its default credential chain (IAM role).
func ResolveAWSCredentials(secret *corev1.Secret) AWSCredentials {
	var c AWSCredentials
	if v, ok := secret.Data["awsAccessKeyId"]; ok {
		c.AccessKeyID = strings.TrimSpace(string(v))
	}
	if v, ok := secret.Data["awsSecretAccessKey"]; ok {
		c.SecretAccessKey = strings.TrimSpace(string(v))
	}
	if v, ok := secret.Data["awsSessionToken"]; ok {
		c.SessionToken = strings.TrimSpace(string(v))
	}
	return c
}

// ValidateAWSConfig checks that all required AWS parameters are present.
func ValidateAWSConfig(spec mlv1alpha1.NodeProvisionSpec) error {
	if spec.Region == "" {
		return fmt.Errorf("spec.region is required for AWS provider")
	}
	if spec.InstanceType == "" {
		return fmt.Errorf("spec.instanceType is required for AWS provider")
	}
	aws := spec.AWSConfig
	if aws == nil {
		return fmt.Errorf("spec.awsConfig is required for AWS provider")
	}
	if aws.AMI == "" {
		return fmt.Errorf("spec.awsConfig.ami is required")
	}
	if aws.SubnetID == "" {
		return fmt.Errorf("spec.awsConfig.subnetId is required")
	}
	return nil
}

// ProvisionResult contains the EC2 instance data returned after a successful launch.
type ProvisionResult struct {
	InstanceID string
	PrivateIP  string
	PublicIP   string
	VpnIP      string
	PublicKey  string
}

// ProvisionEC2Node performs the full AWS provisioning workflow:
//  1. Allocate a VPN IP from the NodeProvisionNetConfig range.
//  2. Generate a WireGuard keypair.
//  3. Register the peer on the VPN server.
//  4. Build a cloud-init script that installs packages, configures VPN, and joins the cluster.
//  5. Launch the EC2 instance with that user-data.
//
// The function is safe to call multiple times for the same node because VPN
// peer registration and IP allocation are idempotent (checked by the caller
// via updateNetConfigStatus before calling this again).
func ProvisionEC2Node(
	ctx context.Context,
	nodeProvision *mlv1alpha1.NodeProvision,
	secret *corev1.Secret,
	vpnServerClient *sshhelper.Client,
	netNodeConfig *mlv1alpha1.NodeProvisionNetConfig,
) (*ProvisionResult, error) {

	name := nodeProvision.Name
	log.Printf("[INFO] NodeProvision/%s: AWS validation successful", name)

	// ── Allocate VPN IP ────────────────────────────────────────────────────
	vpnIP, err := remotenodeprovision.GetNextAvailableIP(
		*netNodeConfig.Spec.VPNRange,
		netNodeConfig.Status.UsedIPAddresses,
	)
	if err != nil {
		return nil, fmt.Errorf("allocating VPN IP: %w", err)
	}
	log.Printf("[INFO] NodeProvision/%s: Assigned VPN IP %s", name, vpnIP)

	// ── Generate WireGuard keypair ─────────────────────────────────────────
	privateKey, publicKey, err := remotenodeprovision.GenerateWireGuardKeyPair()
	if err != nil {
		return nil, fmt.Errorf("generating WireGuard keypair: %w", err)
	}

	// ── Build WireGuard client config ──────────────────────────────────────
	wgConfig, err := remotenodeprovision.BuildClientWGConfig(
		vpnServerClient,
		vpnIP,
		*netNodeConfig.Spec.VPNRange,
		netNodeConfig.Spec.VPNServerPublicConfig.PublicIP,
		netNodeConfig.Spec.VPNServerPublicConfig.VPNPort,
		privateKey,
	)
	if err != nil {
		return nil, fmt.Errorf("building WireGuard client config: %w", err)
	}

	// ── Register peer on VPN server ────────────────────────────────────────
	// Must happen before the instance boots so the server is ready to accept
	// the WireGuard handshake that cloud-init initiates.
	if err := remotenodeprovision.RegisterVPNPeer(vpnServerClient, publicKey, vpnIP); err != nil {
		return nil, fmt.Errorf("registering VPN peer: %w", err)
	}
	log.Printf("[INFO] NodeProvision/%s: VPN peer registered (vpnIP=%s)", name, vpnIP)

	// ── Parse Kubernetes version ───────────────────────────────────────────
	clean := strings.TrimPrefix(netNodeConfig.Spec.SoftwareConfig.KubernetesVersion, "v")
	parts := strings.Split(clean, ".")
	if len(parts) < 2 {
		return nil, fmt.Errorf("invalid kubernetes version: %s", netNodeConfig.Spec.SoftwareConfig.KubernetesVersion)
	}
	crioVersion := fmt.Sprintf("%s.%s", parts[0], parts[1])

	// ── Build cloud-init user-data ─────────────────────────────────────────
	labels := []string{}
	if nodeProvision.Spec.NodeLabel != "" {
		labels = append(labels, fmt.Sprintf("hardware-type=%s", nodeProvision.Spec.NodeLabel))
	}

	userDataB64 := BuildUserData(CloudInitParams{
		WGConfig:               wgConfig,
		VpnIP:                  vpnIP,
		JoinCommand:            netNodeConfig.Status.ClusterJoinCommand,
		KubernetesVersion:      clean,
		KubernetesMinorVersion: crioVersion,
		CRIOVersion:            crioVersion,
		NodeName:               name,
		Labels:                 labels,
	})

	// ── Create EC2 instance ────────────────────────────────────────────────
	creds := ResolveAWSCredentials(secret)
	ec2Client, err := newEC2Client(ctx, nodeProvision.Spec.Region, creds)
	if err != nil {
		return nil, fmt.Errorf("creating EC2 client: %w", err)
	}

	log.Printf("[INFO] NodeProvision/%s: Creating EC2 instance (type=%s region=%s)",
		name, nodeProvision.Spec.InstanceType, nodeProvision.Spec.Region)

	input := buildRunInstancesInput(nodeProvision, userDataB64)
	runOut, err := ec2Client.RunInstances(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("launching EC2 instance: %w", err)
	}
	if len(runOut.Instances) == 0 {
		return nil, fmt.Errorf("RunInstances returned no instances")
	}

	instanceID := aws.ToString(runOut.Instances[0].InstanceId)
	log.Printf("[INFO] NodeProvision/%s: EC2 instance %s created", name, instanceID)

	// ── Tag instance ───────────────────────────────────────────────────────
	if err := tagInstance(ctx, ec2Client, instanceID, nodeProvision); err != nil {
		log.Printf("[WARN] NodeProvision/%s: failed to tag instance: %v", name, err)
	}

	return &ProvisionResult{
		InstanceID: instanceID,
		VpnIP:      vpnIP,
		PublicKey:  publicKey,
	}, nil
}

// WaitForInstanceRunning polls EC2 until the instance reaches the "running"
// state and returns its private and public IPs.
func WaitForInstanceRunning(
	ctx context.Context,
	nodeProvision *mlv1alpha1.NodeProvision,
	secret *corev1.Secret,
	instanceID string,
) (privateIP, publicIP string, err error) {
	name := nodeProvision.Name
	creds := ResolveAWSCredentials(secret)
	ec2Client, err := newEC2Client(ctx, nodeProvision.Spec.Region, creds)
	if err != nil {
		return "", "", fmt.Errorf("creating EC2 client: %w", err)
	}

	log.Printf("[INFO] NodeProvision/%s: Waiting for instance readiness", name)

	out, err := ec2Client.DescribeInstances(ctx, &ec2.DescribeInstancesInput{
		InstanceIds: []string{instanceID},
	})
	if err != nil {
		return "", "", fmt.Errorf("describing instance %s: %w", instanceID, err)
	}
	if len(out.Reservations) == 0 || len(out.Reservations[0].Instances) == 0 {
		return "", "", fmt.Errorf("instance %s not found", instanceID)
	}

	inst := out.Reservations[0].Instances[0]
	if inst.State == nil || inst.State.Name != types.InstanceStateNameRunning {
		return "", "", nil // caller should requeue
	}

	private := aws.ToString(inst.PrivateIpAddress)
	public := aws.ToString(inst.PublicIpAddress)

	log.Printf("[INFO] NodeProvision/%s: Assigned private IP %s", name, private)
	if public != "" {
		log.Printf("[INFO] NodeProvision/%s: Assigned public IP %s", name, public)
	}

	return private, public, nil
}

// TerminateInstance terminates an EC2 instance as part of deprovisioning.
// The call is idempotent — terminating an already-terminated instance is a no-op.
func TerminateInstance(
	ctx context.Context,
	nodeProvision *mlv1alpha1.NodeProvision,
	secret *corev1.Secret,
	instanceID string,
) error {
	name := nodeProvision.Name
	creds := ResolveAWSCredentials(secret)
	ec2Client, err := newEC2Client(ctx, nodeProvision.Spec.Region, creds)
	if err != nil {
		return fmt.Errorf("creating EC2 client: %w", err)
	}

	log.Printf("[INFO] NodeProvision/%s: Terminating EC2 instance %s", name, instanceID)
	_, err = ec2Client.TerminateInstances(ctx, &ec2.TerminateInstancesInput{
		InstanceIds: []string{instanceID},
	})
	if err != nil {
		// Already terminated is fine.
		if strings.Contains(err.Error(), "InvalidInstanceID") {
			log.Printf("[INFO] NodeProvision/%s: Instance %s already gone", name, instanceID)
			return nil
		}
		return fmt.Errorf("terminating instance %s: %w", instanceID, err)
	}
	log.Printf("[INFO] NodeProvision/%s: Instance %s termination initiated", name, instanceID)
	return nil
}

// NetworkConfig holds the resolved AWS network identifiers.
type NetworkConfig struct {
	VPCID           string
	SubnetID        string
	SecurityGroupID string
}

// ResolveOrCreateNetworkConfig checks the region for a default VPC.
// If one exists its first available subnet and default security group are
// returned.  If no default VPC exists one is created first, which also
// automatically creates default subnets and a default security group.
// The returned NetworkConfig can then be used to populate AWSConfig fields
// that the user left unset.
func ResolveOrCreateNetworkConfig(ctx context.Context, region string, creds AWSCredentials) (*NetworkConfig, error) {
	client, err := newEC2Client(ctx, region, creds)
	if err != nil {
		return nil, fmt.Errorf("creating EC2 client: %w", err)
	}

	// ── VPC ──────────────────────────────────────────────────────────────────
	vpcID, err := ensureDefaultVPC(ctx, client, region)
	if err != nil {
		return nil, err
	}
	log.Printf("[INFO] Network resolution: using VPC %s in %s", vpcID, region)

	// ── Subnet ───────────────────────────────────────────────────────────────
	subnetID, err := resolveDefaultSubnet(ctx, client, vpcID)
	if err != nil {
		return nil, err
	}
	log.Printf("[INFO] Network resolution: using subnet %s", subnetID)

	// ── Security group ────────────────────────────────────────────────────────
	sgID, err := resolveDefaultSecurityGroup(ctx, client, vpcID)
	if err != nil {
		return nil, err
	}
	log.Printf("[INFO] Network resolution: using security group %s", sgID)

	return &NetworkConfig{
		VPCID:           vpcID,
		SubnetID:        subnetID,
		SecurityGroupID: sgID,
	}, nil
}

// ensureDefaultVPC returns the ID of the region's default VPC, creating one
// if it does not yet exist.
func ensureDefaultVPC(ctx context.Context, client *ec2.Client, region string) (string, error) {
	out, err := client.DescribeVpcs(ctx, &ec2.DescribeVpcsInput{
		Filters: []types.Filter{
			{Name: aws.String("isDefault"), Values: []string{"true"}},
		},
	})
	if err != nil {
		return "", fmt.Errorf("describing VPCs in %s: %w", region, err)
	}
	if len(out.Vpcs) > 0 {
		return aws.ToString(out.Vpcs[0].VpcId), nil
	}

	log.Printf("[INFO] Network resolution: no default VPC in %s, creating one", region)
	created, err := client.CreateDefaultVpc(ctx, &ec2.CreateDefaultVpcInput{})
	if err != nil {
		return "", fmt.Errorf("creating default VPC in %s: %w", region, err)
	}
	return aws.ToString(created.Vpc.VpcId), nil
}

// resolveDefaultSubnet returns the first available subnet in the given VPC.
// Default subnets are preferred; if none are found any subnet is accepted.
func resolveDefaultSubnet(ctx context.Context, client *ec2.Client, vpcID string) (string, error) {
	out, err := client.DescribeSubnets(ctx, &ec2.DescribeSubnetsInput{
		Filters: []types.Filter{
			{Name: aws.String("vpc-id"), Values: []string{vpcID}},
			{Name: aws.String("defaultForAz"), Values: []string{"true"}},
		},
	})
	if err != nil {
		return "", fmt.Errorf("describing subnets for VPC %s: %w", vpcID, err)
	}
	if len(out.Subnets) > 0 {
		return aws.ToString(out.Subnets[0].SubnetId), nil
	}

	// Fall back to any subnet in the VPC.
	all, err := client.DescribeSubnets(ctx, &ec2.DescribeSubnetsInput{
		Filters: []types.Filter{
			{Name: aws.String("vpc-id"), Values: []string{vpcID}},
		},
	})
	if err != nil {
		return "", fmt.Errorf("describing subnets for VPC %s: %w", vpcID, err)
	}
	if len(all.Subnets) == 0 {
		return "", fmt.Errorf("no subnets found in VPC %s", vpcID)
	}
	return aws.ToString(all.Subnets[0].SubnetId), nil
}

// resolveDefaultSecurityGroup returns the ID of the VPC's default security group.
func resolveDefaultSecurityGroup(ctx context.Context, client *ec2.Client, vpcID string) (string, error) {
	out, err := client.DescribeSecurityGroups(ctx, &ec2.DescribeSecurityGroupsInput{
		Filters: []types.Filter{
			{Name: aws.String("vpc-id"), Values: []string{vpcID}},
			{Name: aws.String("group-name"), Values: []string{"default"}},
		},
	})
	if err != nil {
		return "", fmt.Errorf("describing security groups for VPC %s: %w", vpcID, err)
	}
	if len(out.SecurityGroups) == 0 {
		return "", fmt.Errorf("no default security group found in VPC %s", vpcID)
	}
	return aws.ToString(out.SecurityGroups[0].GroupId), nil
}

// KeyPairResult is returned by ResolveOrCreateKeyPair.
type KeyPairResult struct {
	// KeyPairName is the EC2 key pair name, ready to pass to RunInstances.
	KeyPairName string
	// PrivateKeyPEM is the PKCS#1 PEM-encoded RSA private key.
	// Non-empty only when a new key pair was generated in this call;
	// empty when an existing key pair was reused.
	PrivateKeyPEM string
	// SecretName is the Kubernetes Secret that stores the private key.
	SecretName string
}

// ResolveOrCreateKeyPair ensures an EC2 key pair exists for the node and that
// the corresponding private key is available.  The strategy:
//
//  1. If a K8s Secret named "<npName>-ssh-key" already exists and contains a
//     private key, derive the public key from it and import (or re-import) the
//     key pair into EC2 under the name "nodeprovision-<npName>".
//  2. Otherwise generate a fresh 4096-bit RSA key pair, return the private key
//     PEM so the caller can store it in a Secret, and import the public half
//     into EC2.
//
// The function is idempotent: calling it multiple times for the same node
// results in the same key pair name and the same Secret.
func ResolveOrCreateKeyPair(
	ctx context.Context,
	region string,
	creds AWSCredentials,
	npName string,
	existingPrivKeyPEM string, // non-empty if Secret already exists
) (*KeyPairResult, error) {

	ec2Client, err := newEC2Client(ctx, region, creds)
	if err != nil {
		return nil, fmt.Errorf("creating EC2 client: %w", err)
	}

	keyPairName := "nodeprovision-" + npName
	secretName := npName + "-ssh-key"

	var privKeyPEM string
	var pubKeyBytes []byte // OpenSSH authorized-keys format

	if existingPrivKeyPEM != "" {
		// Derive public key from the stored private key.
		pub, err := publicKeyFromPEM(existingPrivKeyPEM)
		if err != nil {
			return nil, fmt.Errorf("parsing existing private key from secret %q: %w", secretName, err)
		}
		pubKeyBytes = pub
		privKeyPEM = "" // already stored; don't overwrite
	} else {
		// Generate a new RSA key pair.
		priv, pub, err := generateRSAKeyPair()
		if err != nil {
			return nil, fmt.Errorf("generating RSA key pair: %w", err)
		}
		privKeyPEM = priv
		pubKeyBytes = pub
	}

	// Import (upsert) the public key into EC2.  If the key pair already exists
	// with the same public material this is a no-op; if the material changed
	// (e.g. key was regenerated) the old pair is deleted first.
	if err := importKeyPair(ctx, ec2Client, keyPairName, pubKeyBytes); err != nil {
		return nil, err
	}

	log.Printf("[INFO] Key pair resolution: key pair %q ready in %s (secret=%s)", keyPairName, region, secretName)
	return &KeyPairResult{
		KeyPairName:   keyPairName,
		PrivateKeyPEM: privKeyPEM,
		SecretName:    secretName,
	}, nil
}

// importKeyPair imports the public key into EC2 under keyPairName.
// If a key pair with that name already exists it is first deleted so the
// import is always up to date with the stored private key.
func importKeyPair(ctx context.Context, client *ec2.Client, keyPairName string, publicKeyMaterial []byte) error {
	// Check whether the key pair already exists.
	existing, err := client.DescribeKeyPairs(ctx, &ec2.DescribeKeyPairsInput{
		KeyNames: []string{keyPairName},
	})
	if err != nil && !strings.Contains(err.Error(), "InvalidKeyPair.NotFound") {
		return fmt.Errorf("describing key pair %q: %w", keyPairName, err)
	}
	if existing != nil && len(existing.KeyPairs) > 0 {
		// Key pair exists — nothing to do; the public material is already there.
		return nil
	}

	_, err = client.ImportKeyPair(ctx, &ec2.ImportKeyPairInput{
		KeyName:           aws.String(keyPairName),
		PublicKeyMaterial: publicKeyMaterial,
	})
	if err != nil {
		return fmt.Errorf("importing key pair %q: %w", keyPairName, err)
	}
	return nil
}

// generateRSAKeyPair creates a 4096-bit RSA key and returns
// (PKCS#1-PEM private key, OpenSSH-format public key bytes).
func generateRSAKeyPair() (privPEM string, pubAuthorizedKey []byte, err error) {
	privKey, err := rsa.GenerateKey(rand.Reader, 4096)
	if err != nil {
		return "", nil, fmt.Errorf("generating RSA key: %w", err)
	}

	privBytes := x509.MarshalPKCS1PrivateKey(privKey)
	privPEM = string(pem.EncodeToMemory(&pem.Block{
		Type:  "RSA PRIVATE KEY",
		Bytes: privBytes,
	}))

	pubKey, err := ssh.NewPublicKey(&privKey.PublicKey)
	if err != nil {
		return "", nil, fmt.Errorf("deriving SSH public key: %w", err)
	}
	return privPEM, ssh.MarshalAuthorizedKey(pubKey), nil
}

// publicKeyFromPEM derives the OpenSSH authorized-keys public key from a
// PKCS#1 PEM-encoded RSA private key.
func publicKeyFromPEM(privPEM string) ([]byte, error) {
	block, _ := pem.Decode([]byte(privPEM))
	if block == nil {
		return nil, fmt.Errorf("failed to decode PEM block")
	}
	privKey, err := x509.ParsePKCS1PrivateKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parsing PKCS1 private key: %w", err)
	}
	pubKey, err := ssh.NewPublicKey(&privKey.PublicKey)
	if err != nil {
		return nil, fmt.Errorf("deriving SSH public key: %w", err)
	}
	return ssh.MarshalAuthorizedKey(pubKey), nil
}

// ResolveUbuntu22AMI finds the latest Ubuntu 22.04 LTS HVM x86_64 AMI published
// by Canonical in the given region.  Canonical's owner ID is 099720109477.
func ResolveUbuntu22AMI(ctx context.Context, region string, creds AWSCredentials) (string, error) {
	client, err := newEC2Client(ctx, region, creds)
	if err != nil {
		return "", fmt.Errorf("creating EC2 client: %w", err)
	}

	out, err := client.DescribeImages(ctx, &ec2.DescribeImagesInput{
		Owners: []string{"099720109477"}, // Canonical
		Filters: []types.Filter{
			{Name: aws.String("name"), Values: []string{"ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"}},
			{Name: aws.String("state"), Values: []string{"available"}},
			{Name: aws.String("architecture"), Values: []string{"x86_64"}},
			{Name: aws.String("virtualization-type"), Values: []string{"hvm"}},
			{Name: aws.String("root-device-type"), Values: []string{"ebs"}},
		},
	})
	if err != nil {
		return "", fmt.Errorf("describing Ubuntu 22.04 AMIs in %s: %w", region, err)
	}
	if len(out.Images) == 0 {
		return "", fmt.Errorf("no Ubuntu 22.04 LTS AMI found in region %s", region)
	}

	// Sort by CreationDate descending to get the most recent image.
	sort.Slice(out.Images, func(i, j int) bool {
		return aws.ToString(out.Images[i].CreationDate) > aws.ToString(out.Images[j].CreationDate)
	})

	amiID := aws.ToString(out.Images[0].ImageId)
	amiName := aws.ToString(out.Images[0].Name)
	log.Printf("[INFO] AMI resolution: latest Ubuntu 22.04 in %s is %s (%s)", region, amiID, amiName)
	return amiID, nil
}

// nodeLabelInstanceTypes maps nodeLabel values to their default EC2 instance type.
var nodeLabelInstanceTypes = map[string]string{
	"cpu": "t3.xlarge",
	"gpu": "p3.2xlarge",
}

// DefaultInstanceTypeForLabel returns the recommended EC2 instance type for the
// given nodeLabel.  Returns an empty string when no mapping is defined.
func DefaultInstanceTypeForLabel(nodeLabel string) string {
	return nodeLabelInstanceTypes[strings.ToLower(nodeLabel)]
}

// ────────────────────────────────────────────────────────────────────────────
// helpers
// ────────────────────────────────────────────────────────────────────────────

func buildRunInstancesInput(np *mlv1alpha1.NodeProvision, userDataB64 string) *ec2.RunInstancesInput {
	input := &ec2.RunInstancesInput{
		ImageId:      aws.String(np.Spec.AWSConfig.AMI),
		InstanceType: types.InstanceType(np.Spec.InstanceType),
		MinCount:     aws.Int32(1),
		MaxCount:     aws.Int32(1),
		UserData:     aws.String(userDataB64),
		NetworkInterfaces: []types.InstanceNetworkInterfaceSpecification{
			{
				DeviceIndex:              aws.Int32(0),
				SubnetId:                 aws.String(np.Spec.AWSConfig.SubnetID),
				AssociatePublicIpAddress: aws.Bool(true),
			},
		},
	}

	if len(np.Spec.AWSConfig.SecurityGroupIDs) > 0 {
		input.NetworkInterfaces[0].Groups = np.Spec.AWSConfig.SecurityGroupIDs
	}

	if np.Spec.AWSConfig.KeyPairName != "" {
		input.KeyName = aws.String(np.Spec.AWSConfig.KeyPairName)
	}

	if np.Spec.AWSConfig.IAMInstanceProfile != "" {
		input.IamInstanceProfile = &types.IamInstanceProfileSpecification{
			Name: aws.String(np.Spec.AWSConfig.IAMInstanceProfile),
		}
	}

	return input
}

func tagInstance(ctx context.Context, client *ec2.Client, instanceID string, np *mlv1alpha1.NodeProvision) error {
	tags := []types.Tag{
		{Key: aws.String("Name"), Value: aws.String(np.Name)},
		{Key: aws.String("managed-by"), Value: aws.String("node-provision-controller")},
		{Key: aws.String("node-provision-name"), Value: aws.String(np.Name)},
		{Key: aws.String("node-provision-namespace"), Value: aws.String(np.Namespace)},
	}
	for k, v := range np.Spec.AWSConfig.Tags {
		tags = append(tags, types.Tag{Key: aws.String(k), Value: aws.String(v)})
	}

	// Retry tagging with backoff because the instance may not yet be visible.
	var lastErr error
	for i := 0; i < 5; i++ {
		_, err := client.CreateTags(ctx, &ec2.CreateTagsInput{
			Resources: []string{instanceID},
			Tags:      tags,
		})
		if err == nil {
			return nil
		}
		lastErr = err
		time.Sleep(time.Duration(i+1) * 2 * time.Second)
	}
	return lastErr
}
