// Package aws implements AWS EC2 node provisioning for the
// NodeProvision controller.  It follows the same VPN-centric architecture as
// the on-prem provisioner: a WireGuard keypair is generated by the controller,
// the peer is registered on the VPN server via SSH, and the WireGuard client
// config plus the kubeadm join command are embedded in a cloud-init user-data
// script that runs automatically when the EC2 instance first boots.
package aws

import (
	"bytes"
	"context"
	"crypto/md5" //nolint:gosec // EC2 reports imported-key fingerprints as MD5; used for comparison only
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"log"
	"sort"
	"strconv"
	"strings"
	"time"

	awssdk "github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/ec2"
	"github.com/aws/aws-sdk-go-v2/service/ec2/types"
	"github.com/aws/smithy-go"
	"golang.org/x/crypto/ssh"

	mlv1alpha1 "dcn.ssu.ac.kr/infra/api/ml/v1alpha1"
	pkgruntime "dcn.ssu.ac.kr/infra/pkg/runtime"
	sshhelper "dcn.ssu.ac.kr/infra/pkg/ssh"
	onprem "dcn.ssu.ac.kr/infra/provider/onprem"
	corev1 "k8s.io/api/core/v1"
)

// AWSCredentials holds static AWS credentials resolved from a Kubernetes Secret.
// If both fields are empty the SDK falls back to its default credential chain
// (environment variables, instance profile, ~/.aws/credentials).
type AWSCredentials struct {
	AccessKeyID     string
	SecretAccessKey string
	SessionToken    string
}

// newEC2Client builds an EC2 client for the given region.  When creds fields
// are empty the SDK's default credential provider chain is used (IAM role).
func newEC2Client(ctx context.Context, region string, creds AWSCredentials) (*ec2.Client, error) {
	var opts []func(*config.LoadOptions) error
	opts = append(opts, config.WithRegion(region))

	if creds.AccessKeyID != "" && creds.SecretAccessKey != "" {
		opts = append(opts, config.WithCredentialsProvider(
			credentials.NewStaticCredentialsProvider(
				creds.AccessKeyID,
				creds.SecretAccessKey,
				creds.SessionToken,
			),
		))
	}

	cfg, err := config.LoadDefaultConfig(ctx, opts...)
	if err != nil {
		return nil, fmt.Errorf("loading AWS config: %w", err)
	}
	return ec2.NewFromConfig(cfg), nil
}

// ec2LaunchAPI is the slice of the EC2 client ProvisionEC2Node needs (an
// interface so the launch workflow can be unit-tested with a fake).
type ec2LaunchAPI interface {
	ec2DescribeInstancesAPI
	RunInstances(ctx context.Context, params *ec2.RunInstancesInput, optFns ...func(*ec2.Options)) (*ec2.RunInstancesOutput, error)
	CreateTags(ctx context.Context, params *ec2.CreateTagsInput, optFns ...func(*ec2.Options)) (*ec2.CreateTagsOutput, error)
}

// newLaunchClient builds the EC2 client used by ProvisionEC2Node; tests replace it.
var newLaunchClient = func(ctx context.Context, region string, creds AWSCredentials) (ec2LaunchAPI, error) {
	return newEC2Client(ctx, region, creds)
}

// ResolveAWSCredentials extracts AWS static credentials from a secret.
// If the secret does not contain the expected keys the returned struct is
// zero-valued and the SDK will use its default credential chain (IAM role).
func ResolveAWSCredentials(secret *corev1.Secret) AWSCredentials {
	var c AWSCredentials
	if v, ok := secret.Data["awsAccessKeyId"]; ok {
		c.AccessKeyID = strings.TrimSpace(string(v))
	}
	if v, ok := secret.Data["awsSecretAccessKey"]; ok {
		c.SecretAccessKey = strings.TrimSpace(string(v))
	}
	if v, ok := secret.Data["awsSessionToken"]; ok {
		c.SessionToken = strings.TrimSpace(string(v))
	}
	return c
}

// IsAWSAuthFailure reports whether err is an AWS AuthFailure or
// InvalidClientTokenId response — both indicate that the credentials
// presented to the AWS API were rejected as invalid or expired.
func IsAWSAuthFailure(err error) bool {
	var apiErr *smithy.GenericAPIError
	if errors.As(err, &apiErr) {
		switch apiErr.Code {
		case "AuthFailure", "InvalidClientTokenId":
			return true
		}
	}
	return false
}

// StaticCredsNoSession returns a copy of creds with SessionToken cleared.
// Use this as a last-resort fallback when a cached STS session is expired:
// if the IAM key itself is still valid and the policy does not require MFA,
// a bare access-key + secret call will succeed.
func StaticCredsNoSession(creds AWSCredentials) AWSCredentials {
	return AWSCredentials{
		AccessKeyID:     creds.AccessKeyID,
		SecretAccessKey: creds.SecretAccessKey,
	}
}

// ValidateAWSConfig checks that all required AWS parameters are present.
func ValidateAWSConfig(spec mlv1alpha1.NodeProvisionSpec) error {
	if spec.Region == "" {
		return fmt.Errorf("spec.region is required for AWS provider")
	}
	if spec.InstanceType == "" {
		return fmt.Errorf("spec.instanceType is required for AWS provider")
	}
	awsCfg := spec.AWSConfig
	if awsCfg == nil {
		return fmt.Errorf("spec.awsConfig is required for AWS provider")
	}
	if awsCfg.AMI == "" {
		return fmt.Errorf("spec.awsConfig.ami is required")
	}
	if awsCfg.SubnetID == "" {
		return fmt.Errorf("spec.awsConfig.subnetId is required")
	}
	return nil
}

// ProvisionResult contains the EC2 instance data returned after a successful launch.
type ProvisionResult struct {
	InstanceID string
	PrivateIP  string
	PublicIP   string
	VpnIP      string
	PublicKey  string
	// Adopted is true when ProvisionEC2Node found an instance already launched
	// for this NodeProvision (by UID tag) and did NOT allocate a VPN peer or
	// launch another one. VpnIP/PublicKey are then empty: the caller must
	// recover the peer that was recorded for that instance (see the
	// controller's adoption path).
	Adopted bool
}

// ErrInstanceAlreadyLaunched is returned by ProvisionEC2Node when RunInstances
// reports that an instance for this NodeProvision's client token already
// exists with different parameters (IdempotentParameterMismatch), e.g. a launch
// whose response was lost. Any VPN peer registered for the rejected attempt has
// been released. The caller should requeue WITHOUT counting a failure: the next
// reconcile finds and adopts the existing instance by its UID tag.
var ErrInstanceAlreadyLaunched = errors.New("an EC2 instance for this NodeProvision was already launched; adopt it instead of launching another")

// nodeProvisionUIDTag is the EC2 tag that ties an instance to the NodeProvision
// that launched it (used for adoption/cleanup when status never recorded the
// instance ID, see FindInstanceIDByNodeProvision).
const nodeProvisionUIDTag = "ml.dcn.ssu.ac.kr/nodeprovision-uid"

// ProvisionEC2Node performs the full AWS provisioning workflow (the VPN steps
// are skipped when nodeProvision.Spec.DisableVPN is set, in which case
// vpnServerClient may be nil):
//
//  0. Look for an existing non-terminated instance tagged with this
//     NodeProvision's UID. If there is one, return it with Adopted=true and do
//     NOTHING else: no VPN peer is allocated and nothing is launched (the
//     controller recovers the peer that was recorded for that instance under
//     this node's name).
//  1. Allocate a VPN IP from the NodeProvisionNetConfig range.
//  2. Generate a WireGuard keypair.
//  3. Register the peer on the VPN server.
//  4. Build a cloud-init script that installs packages, configures VPN, and joins the cluster.
//  5. Launch the EC2 instance with that user-data.
//
// Contract for callers:
//   - Once the VPN peer is registered, every error return also carries a non-nil
//     *ProvisionResult holding VpnIP/PublicKey so the caller can persist them and
//     release the peer later. The user-data is rendered and validated BEFORE
//     any peer is registered or RunInstances is called; invalid parameters fail
//     the call without side effects.
//   - The instance is tagged (instance, volume and Name) with the NodeProvision
//     UID at launch, and RunInstances uses a ClientToken derived from the UID and
//     Status.ProvisionRetryCount (see clientTokenForAttempt): a retry of the same
//     attempt after a crash between RunInstances and the status write is
//     idempotent, while a relaunch after a failed attempt (the instance was
//     terminated) uses a fresh token instead of hitting
//     IdempotentParameterMismatch.
//   - If RunInstances still reports IdempotentParameterMismatch (an instance for
//     the token exists but is not yet visible to DescribeInstances — EC2's
//     eventual consistency), the peer registered for this attempt is released
//     (onprem.UnregisterVPNPeer, best effort) and the returned error wraps
//     ErrInstanceAlreadyLaunched with an EMPTY, non-nil result. The caller must
//     requeue without counting a failure; the next reconcile adopts the
//     instance (step 0).
func ProvisionEC2Node(
	ctx context.Context,
	nodeProvision *mlv1alpha1.NodeProvision,
	creds AWSCredentials,
	vpnServerClient *sshhelper.Client,
	netNodeConfig *mlv1alpha1.NodeProvisionNetConfig,
	runtimeCfg pkgruntime.Config,
) (*ProvisionResult, error) {

	name := nodeProvision.Name
	log.Printf("[INFO] NodeProvision/%s: AWS validation successful", name)

	noVPN := nodeProvision.Spec.DisableVPN

	// ── Parse + validate everything that needs no side effects first ───────
	clean := strings.TrimPrefix(netNodeConfig.Spec.SoftwareConfig.KubernetesVersion, "v")
	parts := strings.Split(clean, ".")
	if len(parts) < 2 {
		return nil, fmt.Errorf("invalid kubernetes version: %s", netNodeConfig.Spec.SoftwareConfig.KubernetesVersion)
	}
	crioVersion := fmt.Sprintf("%s.%s", parts[0], parts[1])

	params := buildCloudInitParams(nodeProvision, netNodeConfig.Status.ClusterJoinCommand, clean, crioVersion, runtimeCfg)
	insecureHosts, err := onprem.InsecureRegistryHosts(netNodeConfig.Spec.SoftwareConfig)
	if err != nil {
		return nil, fmt.Errorf("NodeProvisionNetConfig softwareConfig.%w", err)
	}
	params.InsecureRegistries = insecureHosts
	// Dry-run the render with placeholder VPN values so bad input is rejected
	// before a VPN peer is allocated/registered.
	dry := params
	if !noVPN {
		dry.WGConfig = "[Interface]\n"
		dry.VpnIP = "10.0.0.1"
	}
	if _, err := BuildUserDataE(dry); err != nil {
		return nil, fmt.Errorf("building cloud-init user-data: %w", err)
	}
	if !noVPN {
		if netNodeConfig.Spec.VPNRange == nil || *netNodeConfig.Spec.VPNRange == "" {
			return nil, fmt.Errorf("NodeProvisionNetConfig has no vpnRange configured")
		}
		if vpnServerClient == nil {
			return nil, fmt.Errorf("VPN server connection is required unless spec.disableVPN is set")
		}
	}

	ec2Client, err := newLaunchClient(ctx, nodeProvision.Spec.Region, creds)
	if err != nil {
		return nil, fmt.Errorf("creating EC2 client: %w", err)
	}

	// ── Adopt an instance a previous (crashed) attempt already launched ────
	// This MUST come before any VPN peer is allocated: adopting needs no new
	// peer, and registering one first would leak it.
	existingID, err := findInstanceID(ctx, ec2Client, string(nodeProvision.UID))
	if err != nil {
		return nil, fmt.Errorf("checking for an existing instance: %w", err)
	}
	if existingID != "" {
		log.Printf("[INFO] NodeProvision/%s: adopting existing EC2 instance %s (no VPN peer allocated)", name, existingID)
		return &ProvisionResult{InstanceID: existingID, Adopted: true}, nil
	}

	var (
		vpnIP     string
		publicKey string
	)
	if noVPN {
		// The node picks up its own private IP from instance metadata at boot;
		// no VPN IP is allocated and no peer is registered.
		log.Printf("[INFO] NodeProvision/%s: spec.disableVPN set — skipping VPN allocation", name)
	} else {
		vpnRange := *netNodeConfig.Spec.VPNRange

		// ── Allocate VPN IP, generate keypair, register the peer ──────────────
		// Runs under the process-wide VPN allocation lock (shared with the
		// on-prem provisioner). AllocateVPNIP cross-checks both the CR's
		// UsedIPAddresses and the live WireGuard peer list on the server.
		// Registration must happen before the instance boots so the server is
		// ready to accept the WireGuard handshake that cloud-init initiates.
		peer, err := onprem.AllocateAndRegisterVPNPeer(
			ctx,
			vpnServerClient,
			vpnRange,
			netNodeConfig.Status.UsedIPAddresses,
			netNodeConfig.Spec.VPNServerPublicConfig.PublicIP,
			parsePort(netNodeConfig.Spec.VPNServerPublicConfig.VPNPort, 51820),
		)
		if err != nil {
			return nil, err
		}
		vpnIP, publicKey = peer.IP, peer.PublicKey
		params.WGConfig = peer.WGConfig
		params.VpnIP = vpnIP
		log.Printf("[INFO] NodeProvision/%s: VPN peer registered (vpnIP=%s)", name, vpnIP)
	}

	// vpnResult carries VPN allocation data so the caller can persist it even
	// if EC2 launch fails — preventing orphaned peers on retry.
	vpnResult := &ProvisionResult{VpnIP: vpnIP, PublicKey: publicKey}

	// ── Build cloud-init user-data (validated; fails before RunInstances) ──
	userDataB64, err := BuildUserDataE(params)
	if err != nil {
		return vpnResult, fmt.Errorf("building cloud-init user-data: %w", err)
	}

	// ── Create EC2 instance ────────────────────────────────────────────────
	log.Printf("[INFO] NodeProvision/%s: Creating EC2 instance (type=%s region=%s)",
		name, nodeProvision.Spec.InstanceType, nodeProvision.Spec.Region)

	input := buildRunInstancesInput(nodeProvision, userDataB64)
	runOut, err := ec2Client.RunInstances(ctx, input)
	if err != nil {
		if isIdempotentParameterMismatch(err) {
			// An instance for this ClientToken exists but DescribeInstances did not
			// show it yet. The peer registered for THIS attempt will never be
			// used: release it (best effort) and let the next reconcile adopt.
			if publicKey != "" {
				if rerr := onprem.UnregisterVPNPeer(vpnServerClient, publicKey); rerr != nil {
					log.Printf("[WARN] NodeProvision/%s: could not release VPN peer %s after IdempotentParameterMismatch: %v", name, publicKey, rerr)
				}
			}
			return &ProvisionResult{}, fmt.Errorf("%w: RunInstances: %v", ErrInstanceAlreadyLaunched, err)
		}
		return vpnResult, fmt.Errorf("launching EC2 instance: %w", err)
	}
	if len(runOut.Instances) == 0 {
		return vpnResult, fmt.Errorf("RunInstances returned no instances")
	}

	instanceID := awssdk.ToString(runOut.Instances[0].InstanceId)
	vpnResult.InstanceID = instanceID
	log.Printf("[INFO] NodeProvision/%s: EC2 instance %s created", name, instanceID)

	// ── Apply user-supplied tags (best effort) ─────────────────────────────
	// Controller tags were applied atomically at launch via TagSpecifications.
	if err := tagInstance(ctx, ec2Client, instanceID, nodeProvision); err != nil {
		log.Printf("[WARN] NodeProvision/%s: failed to tag instance: %v", name, err)
	}

	return vpnResult, nil
}

// isIdempotentParameterMismatch reports whether err is EC2's
// IdempotentParameterMismatch (same ClientToken, different launch parameters).
func isIdempotentParameterMismatch(err error) bool {
	var apiErr smithy.APIError
	return errors.As(err, &apiErr) && apiErr.ErrorCode() == "IdempotentParameterMismatch"
}

// buildCloudInitParams assembles the cloud-init parameters for a NodeProvision.
// GPU-ness comes from the single shared rule IsGPUNode (hardwareType decides
// when set, else nodeLabel containing "gpu").
func buildCloudInitParams(np *mlv1alpha1.NodeProvision, joinCommand, kubernetesVersion, kubernetesMinor string, runtimeCfg pkgruntime.Config) CloudInitParams {
	labels := []string{}
	if np.Spec.NodeLabel != "" {
		labels = append(labels, fmt.Sprintf("hardware-type=%s", np.Spec.NodeLabel))
	}
	return CloudInitParams{
		NoVPN:                  np.Spec.DisableVPN,
		JoinCommand:            joinCommand,
		KubernetesVersion:      kubernetesVersion,
		KubernetesMinorVersion: kubernetesMinor,
		NodeName:               np.Name,
		Labels:                 labels,
		SSHUsername:            np.Spec.SSHUsernameOverride,
		IsGPUNode:              IsGPUNode(np),
		RuntimeRegistryUser:    runtimeCfg.Username,
		RuntimeRegistryToken:   runtimeCfg.Token,
		RuntimeRegistry:        runtimeCfg.Registry,
		RuntimeRepository:      runtimeCfg.Repository,
		RuntimeVersion:         runtimeCfg.Version,
		RuntimeOSVariant:       runtimeCfg.OSVariant,
		RuntimeOrasVersion:     runtimeCfg.OrasVersion,
	}
}

// WaitForInstanceRunning polls EC2 until the instance reaches the "running"
// state and returns its private and public IPs.
func WaitForInstanceRunning(
	ctx context.Context,
	nodeProvision *mlv1alpha1.NodeProvision,
	creds AWSCredentials,
	instanceID string,
) (privateIP, publicIP string, err error) {
	name := nodeProvision.Name
	ec2Client, err := newEC2Client(ctx, nodeProvision.Spec.Region, creds)
	if err != nil {
		return "", "", fmt.Errorf("creating EC2 client: %w", err)
	}

	log.Printf("[INFO] NodeProvision/%s: Waiting for instance readiness", name)

	out, err := ec2Client.DescribeInstances(ctx, &ec2.DescribeInstancesInput{
		InstanceIds: []string{instanceID},
	})
	if err != nil {
		return "", "", fmt.Errorf("describing instance %s: %w", instanceID, err)
	}
	if len(out.Reservations) == 0 || len(out.Reservations[0].Instances) == 0 {
		return "", "", fmt.Errorf("instance %s not found", instanceID)
	}

	inst := out.Reservations[0].Instances[0]
	if inst.State == nil {
		return "", "", nil // state not yet reported, caller should requeue
	}
	switch inst.State.Name {
	case types.InstanceStateNameRunning:
		// fall through to read IP addresses below
	case types.InstanceStateNameTerminated, types.InstanceStateNameStopped,
		types.InstanceStateNameStopping, types.InstanceStateNameShuttingDown:
		// These states are never followed by Running again (barring an explicit
		// StartInstances call this controller never makes) — surface an error so
		// the caller fails the NodeProvision instead of polling forever.
		return "", "", fmt.Errorf("instance %s entered terminal state %q and will never become running",
			instanceID, inst.State.Name)
	default:
		// e.g. Pending — still launching, caller should requeue
		return "", "", nil
	}

	private := awssdk.ToString(inst.PrivateIpAddress)
	public := awssdk.ToString(inst.PublicIpAddress)

	log.Printf("[INFO] NodeProvision/%s: Assigned private IP %s", name, private)
	if public != "" {
		log.Printf("[INFO] NodeProvision/%s: Assigned public IP %s", name, public)
	}

	return private, public, nil
}

// TerminateInstance terminates an EC2 instance as part of deprovisioning.
// The call is idempotent — terminating an already-terminated instance is a no-op.
func TerminateInstance(
	ctx context.Context,
	nodeProvision *mlv1alpha1.NodeProvision,
	creds AWSCredentials,
	instanceID string,
) error {
	name := nodeProvision.Name
	ec2Client, err := newEC2Client(ctx, nodeProvision.Spec.Region, creds)
	if err != nil {
		return fmt.Errorf("creating EC2 client: %w", err)
	}

	log.Printf("[INFO] NodeProvision/%s: Terminating EC2 instance %s", name, instanceID)
	_, err = ec2Client.TerminateInstances(ctx, &ec2.TerminateInstancesInput{
		InstanceIds: []string{instanceID},
	})
	if err != nil {
		// Already terminated is fine.
		if strings.Contains(err.Error(), "InvalidInstanceID") {
			log.Printf("[INFO] NodeProvision/%s: Instance %s already gone", name, instanceID)
			return nil
		}
		return fmt.Errorf("terminating instance %s: %w", instanceID, err)
	}
	log.Printf("[INFO] NodeProvision/%s: Instance %s termination initiated", name, instanceID)
	return nil
}

// NetworkConfig holds the resolved AWS network identifiers.
type NetworkConfig struct {
	VPCID           string
	SubnetID        string
	SecurityGroupID string
}

// ResolveOrCreateNetworkConfig checks the region for a default VPC.
// If one exists its first available subnet and default security group are
// returned.  If no default VPC exists one is created first, which also
// automatically creates default subnets and a default security group.
// The returned NetworkConfig can then be used to populate AWSConfig fields
// that the user left unset.
//
// includeWireGuard controls whether the default security group is opened for
// WireGuard (UDP 51820); pass false for clusters that run without a VPN.
func ResolveOrCreateNetworkConfig(ctx context.Context, region string, creds AWSCredentials, includeWireGuard bool) (*NetworkConfig, error) {
	client, err := newEC2Client(ctx, region, creds)
	if err != nil {
		return nil, fmt.Errorf("creating EC2 client: %w", err)
	}

	// ── VPC ──────────────────────────────────────────────────────────────────
	vpcID, err := ensureDefaultVPC(ctx, client, region)
	if err != nil {
		return nil, err
	}
	log.Printf("[INFO] Network resolution: using VPC %s in %s", vpcID, region)

	// ── Subnet ───────────────────────────────────────────────────────────────
	subnetID, err := resolveDefaultSubnet(ctx, client, vpcID)
	if err != nil {
		return nil, err
	}
	log.Printf("[INFO] Network resolution: using subnet %s", subnetID)

	// ── Security group ────────────────────────────────────────────────────────
	sgID, err := resolveDefaultSecurityGroup(ctx, client, vpcID, includeWireGuard)
	if err != nil {
		return nil, err
	}
	log.Printf("[INFO] Network resolution: using security group %s", sgID)

	return &NetworkConfig{
		VPCID:           vpcID,
		SubnetID:        subnetID,
		SecurityGroupID: sgID,
	}, nil
}

// ensureDefaultVPC returns the ID of the region's default VPC, creating one
// if it does not yet exist.
func ensureDefaultVPC(ctx context.Context, client *ec2.Client, region string) (string, error) {
	out, err := client.DescribeVpcs(ctx, &ec2.DescribeVpcsInput{
		Filters: []types.Filter{
			{Name: awssdk.String("isDefault"), Values: []string{"true"}},
		},
	})
	if err != nil {
		return "", fmt.Errorf("describing VPCs in %s: %w", region, err)
	}
	if len(out.Vpcs) > 0 {
		return awssdk.ToString(out.Vpcs[0].VpcId), nil
	}

	log.Printf("[INFO] Network resolution: no default VPC in %s, creating one", region)
	created, err := client.CreateDefaultVpc(ctx, &ec2.CreateDefaultVpcInput{})
	if err != nil {
		return "", fmt.Errorf("creating default VPC in %s: %w", region, err)
	}
	if created.Vpc == nil {
		return "", fmt.Errorf("CreateDefaultVpc returned nil Vpc in %s", region)
	}
	return awssdk.ToString(created.Vpc.VpcId), nil
}

// resolveDefaultSubnet returns the first available subnet in the given VPC.
// Default subnets are preferred; if none are found any subnet is accepted.
func resolveDefaultSubnet(ctx context.Context, client *ec2.Client, vpcID string) (string, error) {
	out, err := client.DescribeSubnets(ctx, &ec2.DescribeSubnetsInput{
		Filters: []types.Filter{
			{Name: awssdk.String("vpc-id"), Values: []string{vpcID}},
			{Name: awssdk.String("defaultForAz"), Values: []string{"true"}},
		},
	})
	if err != nil {
		return "", fmt.Errorf("describing subnets for VPC %s: %w", vpcID, err)
	}
	if len(out.Subnets) > 0 {
		return awssdk.ToString(out.Subnets[0].SubnetId), nil
	}

	// Fall back to any subnet in the VPC.
	all, err := client.DescribeSubnets(ctx, &ec2.DescribeSubnetsInput{
		Filters: []types.Filter{
			{Name: awssdk.String("vpc-id"), Values: []string{vpcID}},
		},
	})
	if err != nil {
		return "", fmt.Errorf("describing subnets for VPC %s: %w", vpcID, err)
	}
	if len(all.Subnets) == 0 {
		return "", fmt.Errorf("no subnets found in VPC %s", vpcID)
	}
	return awssdk.ToString(all.Subnets[0].SubnetId), nil
}

// resolveDefaultSecurityGroup returns the ID of the VPC's default security group
// and ensures it has inbound rules for SSH (TCP 22) and, when includeWireGuard
// is set, WireGuard (UDP 51820).
func resolveDefaultSecurityGroup(ctx context.Context, client *ec2.Client, vpcID string, includeWireGuard bool) (string, error) {
	out, err := client.DescribeSecurityGroups(ctx, &ec2.DescribeSecurityGroupsInput{
		Filters: []types.Filter{
			{Name: awssdk.String("vpc-id"), Values: []string{vpcID}},
			{Name: awssdk.String("group-name"), Values: []string{"default"}},
		},
	})
	if err != nil {
		return "", fmt.Errorf("describing security groups for VPC %s: %w", vpcID, err)
	}
	if len(out.SecurityGroups) == 0 {
		return "", fmt.Errorf("no default security group found in VPC %s", vpcID)
	}
	sgID := awssdk.ToString(out.SecurityGroups[0].GroupId)
	sg := out.SecurityGroups[0]
	if err := ensureNodeIngressRules(ctx, client, sgID, sg.IpPermissions, includeWireGuard); err != nil {
		log.Printf("[WARN] Security group %s: could not ensure ingress rules: %v", sgID, err)
	}
	return sgID, nil
}

// ingressRule is a single-port ingress rule the node security group needs.
type ingressRule struct {
	proto string
	port  int32
}

// requiredIngressRules lists the ingress rules nodes need: SSH always,
// WireGuard only when the cluster uses a VPN.
func requiredIngressRules(includeWireGuard bool) []ingressRule {
	rules := []ingressRule{{"tcp", 22}} // SSH
	if includeWireGuard {
		rules = append(rules, ingressRule{"udp", 51820}) // WireGuard
	}
	return rules
}

// ensureNodeIngressRules adds TCP 22 (SSH) and UDP 51820 (WireGuard) ingress rules
// to the security group if they are not already present.  Existing rules are never
// removed.  Duplicate-rule errors from AWS are silently ignored.
func ensureNodeIngressRules(ctx context.Context, client *ec2.Client, sgID string, existing []types.IpPermission, includeWireGuard bool) error {
	present := make(map[ingressRule]bool)
	for _, perm := range existing {
		if perm.FromPort == nil || perm.ToPort == nil || perm.IpProtocol == nil {
			continue
		}
		if *perm.FromPort == *perm.ToPort {
			k := ingressRule{proto: *perm.IpProtocol, port: *perm.FromPort}
			for _, r := range perm.IpRanges {
				if awssdk.ToString(r.CidrIp) == "0.0.0.0/0" {
					present[k] = true
				}
			}
		}
	}

	var toAdd []types.IpPermission
	for _, r := range requiredIngressRules(includeWireGuard) {
		if !present[r] {
			port := r.port
			toAdd = append(toAdd, types.IpPermission{
				IpProtocol: awssdk.String(r.proto),
				FromPort:   awssdk.Int32(port),
				ToPort:     awssdk.Int32(port),
				IpRanges: []types.IpRange{
					{CidrIp: awssdk.String("0.0.0.0/0"), Description: awssdk.String("node-provision-controller")},
				},
			})
		}
	}
	if len(toAdd) == 0 {
		return nil
	}

	_, err := client.AuthorizeSecurityGroupIngress(ctx, &ec2.AuthorizeSecurityGroupIngressInput{
		GroupId:       awssdk.String(sgID),
		IpPermissions: toAdd,
	})
	if err != nil && !strings.Contains(err.Error(), "InvalidPermission.Duplicate") {
		return fmt.Errorf("authorizing ingress on %s: %w", sgID, err)
	}
	for _, r := range toAdd {
		log.Printf("[WARN] Security group %s: added WORLD-OPEN ingress rule %s/%d from 0.0.0.0/0 (the VPC's default security group is shared; restrict it if this is not intended)",
			sgID, awssdk.ToString(r.IpProtocol), awssdk.ToInt32(r.FromPort))
	}
	return nil
}

// KeyPairResult is returned by ResolveOrCreateKeyPair.
type KeyPairResult struct {
	// KeyPairName is the EC2 key pair name, ready to pass to RunInstances.
	KeyPairName string
	// PrivateKeyPEM is the PKCS#1 PEM-encoded RSA private key.
	// Non-empty only when a new key pair was generated in this call;
	// empty when an existing key pair was reused.
	PrivateKeyPEM string
	// SecretName is the Kubernetes Secret that stores the private key.
	SecretName string
}

// ResolveOrCreateKeyPair ensures an EC2 key pair exists for the node and that
// the corresponding private key is available.  The strategy:
//
//  1. If a K8s Secret named "<npName>-ssh-key" already exists and contains a
//     private key, derive the public key from it and import (or re-import) the
//     key pair into EC2 under the name "nodeprovision-<npName>".
//  2. Otherwise generate a fresh 4096-bit RSA key pair, return the private key
//     PEM so the caller can store it in a Secret, and import the public half
//     into EC2.
//
// The function is idempotent: calling it multiple times for the same node
// results in the same key pair name and the same Secret.
func ResolveOrCreateKeyPair(
	ctx context.Context,
	region string,
	creds AWSCredentials,
	npName string,
	existingPrivKeyPEM string, // non-empty if Secret already exists
) (*KeyPairResult, error) {

	ec2Client, err := newEC2Client(ctx, region, creds)
	if err != nil {
		return nil, fmt.Errorf("creating EC2 client: %w", err)
	}

	keyPairName := "nodeprovision-" + npName
	secretName := npName + "-ssh-key"

	var privKeyPEM string
	var pubKeyBytes []byte // OpenSSH authorized-keys format

	if existingPrivKeyPEM != "" {
		// Derive public key from the stored private key.
		pub, err := publicKeyFromPEM(existingPrivKeyPEM)
		if err != nil {
			return nil, fmt.Errorf("parsing existing private key from secret %q: %w", secretName, err)
		}
		pubKeyBytes = pub
		privKeyPEM = "" // already stored; don't overwrite
	} else {
		// Generate a new RSA key pair.
		priv, pub, err := generateRSAKeyPair()
		if err != nil {
			return nil, fmt.Errorf("generating RSA key pair: %w", err)
		}
		privKeyPEM = priv
		pubKeyBytes = pub
	}

	// Import (upsert) the public key into EC2.  If the key pair already exists
	// with the same public material this is a no-op; if the material changed
	// (e.g. key was regenerated) the old pair is deleted first.
	if err := importKeyPair(ctx, ec2Client, keyPairName, pubKeyBytes); err != nil {
		return nil, err
	}

	log.Printf("[INFO] Key pair resolution: key pair %q ready in %s (secret=%s)", keyPairName, region, secretName)
	return &KeyPairResult{
		KeyPairName:   keyPairName,
		PrivateKeyPEM: privKeyPEM,
		SecretName:    secretName,
	}, nil
}

// importKeyPair imports the public key into EC2 under keyPairName.
// If a key pair with that name already exists and its material matches the
// supplied public key nothing is done; if it differs it is deleted and
// re-imported so the EC2 key pair always matches the stored private key.
func importKeyPair(ctx context.Context, client *ec2.Client, keyPairName string, publicKeyMaterial []byte) error {
	// Check whether the key pair already exists.
	existing, err := client.DescribeKeyPairs(ctx, &ec2.DescribeKeyPairsInput{
		KeyNames:         []string{keyPairName},
		IncludePublicKey: awssdk.Bool(true),
	})
	if err != nil && !strings.Contains(err.Error(), "InvalidKeyPair.NotFound") {
		return fmt.Errorf("describing key pair %q: %w", keyPairName, err)
	}
	if existing != nil && len(existing.KeyPairs) > 0 {
		kp := existing.KeyPairs[0]
		if keyPairMatches(kp.PublicKey, kp.KeyFingerprint, publicKeyMaterial) {
			return nil // same public material already imported
		}
		log.Printf("[INFO] Key pair %q exists with different public key material; deleting and re-importing", keyPairName)
		if _, derr := client.DeleteKeyPair(ctx, &ec2.DeleteKeyPairInput{KeyName: awssdk.String(keyPairName)}); derr != nil {
			return fmt.Errorf("deleting stale key pair %q: %w", keyPairName, derr)
		}
	}

	_, err = client.ImportKeyPair(ctx, &ec2.ImportKeyPairInput{
		KeyName:           awssdk.String(keyPairName),
		PublicKeyMaterial: publicKeyMaterial,
	})
	if err != nil {
		return fmt.Errorf("importing key pair %q: %w", keyPairName, err)
	}
	return nil
}

// keyPairMatches reports whether an existing EC2 key pair (described by its
// public key text and/or fingerprint) carries the same public key as want
// (OpenSSH authorized_keys format). When EC2 returns the public key it is
// compared directly (key type + base64 body, ignoring the comment); otherwise
// the fingerprint is compared against both fingerprint formats EC2 uses for
// imported keys (MD5 of the DER SubjectPublicKeyInfo, or SHA256 of the SSH
// wire format). Anything that cannot be positively matched counts as a
// mismatch so the pair is re-imported.
func keyPairMatches(existingPublicKey, existingFingerprint *string, want []byte) bool {
	wantKey, _, _, _, err := ssh.ParseAuthorizedKey(want)
	if err != nil {
		return false
	}
	if pk := strings.TrimSpace(awssdk.ToString(existingPublicKey)); pk != "" {
		if got, _, _, _, perr := ssh.ParseAuthorizedKey([]byte(pk)); perr == nil {
			return bytes.Equal(got.Marshal(), wantKey.Marshal())
		}
	}
	fp := strings.TrimSpace(awssdk.ToString(existingFingerprint))
	if fp == "" {
		return false
	}
	for _, cand := range publicKeyFingerprints(wantKey) {
		if strings.EqualFold(cand, fp) {
			return true
		}
	}
	return false
}

// publicKeyFingerprints returns the fingerprints EC2 may report for an
// imported copy of key.
func publicKeyFingerprints(key ssh.PublicKey) []string {
	var out []string
	if ck, ok := key.(ssh.CryptoPublicKey); ok {
		if der, err := x509.MarshalPKIXPublicKey(ck.CryptoPublicKey()); err == nil {
			sum := md5.Sum(der)
			parts := make([]string, len(sum))
			for i, b := range sum {
				parts[i] = fmt.Sprintf("%02x", b)
			}
			out = append(out, strings.Join(parts, ":"))
		}
	}
	out = append(out, ssh.FingerprintSHA256(key))
	return out
}

// generateRSAKeyPair creates a 4096-bit RSA key and returns
// (PKCS#1-PEM private key, OpenSSH-format public key bytes).
func generateRSAKeyPair() (privPEM string, pubAuthorizedKey []byte, err error) {
	privKey, err := rsa.GenerateKey(rand.Reader, 4096)
	if err != nil {
		return "", nil, fmt.Errorf("generating RSA key: %w", err)
	}

	privBytes := x509.MarshalPKCS1PrivateKey(privKey)
	privPEM = string(pem.EncodeToMemory(&pem.Block{
		Type:  "RSA PRIVATE KEY",
		Bytes: privBytes,
	}))

	pubKey, err := ssh.NewPublicKey(&privKey.PublicKey)
	if err != nil {
		return "", nil, fmt.Errorf("deriving SSH public key: %w", err)
	}
	return privPEM, ssh.MarshalAuthorizedKey(pubKey), nil
}

// publicKeyFromPEM derives the OpenSSH authorized-keys public key from a
// PKCS#1 PEM-encoded RSA private key.
func publicKeyFromPEM(privPEM string) ([]byte, error) {
	block, _ := pem.Decode([]byte(privPEM))
	if block == nil {
		return nil, fmt.Errorf("failed to decode PEM block")
	}
	privKey, err := x509.ParsePKCS1PrivateKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parsing PKCS1 private key: %w", err)
	}
	pubKey, err := ssh.NewPublicKey(&privKey.PublicKey)
	if err != nil {
		return nil, fmt.Errorf("deriving SSH public key: %w", err)
	}
	return ssh.MarshalAuthorizedKey(pubKey), nil
}

// ResolveUbuntu22AMI finds the latest Ubuntu 22.04 LTS HVM x86_64 AMI published
// by Canonical in the given region.  Canonical's owner ID is 099720109477.
func ResolveUbuntu22AMI(ctx context.Context, region string, creds AWSCredentials) (string, error) {
	client, err := newEC2Client(ctx, region, creds)
	if err != nil {
		return "", fmt.Errorf("creating EC2 client: %w", err)
	}

	out, err := client.DescribeImages(ctx, &ec2.DescribeImagesInput{
		Owners: []string{"099720109477"}, // Canonical
		Filters: []types.Filter{
			{Name: awssdk.String("name"), Values: []string{"ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"}},
			{Name: awssdk.String("state"), Values: []string{"available"}},
			{Name: awssdk.String("architecture"), Values: []string{"x86_64"}},
			{Name: awssdk.String("virtualization-type"), Values: []string{"hvm"}},
			{Name: awssdk.String("root-device-type"), Values: []string{"ebs"}},
		},
	})
	if err != nil {
		return "", fmt.Errorf("describing Ubuntu 22.04 AMIs in %s: %w", region, err)
	}
	if len(out.Images) == 0 {
		return "", fmt.Errorf("no Ubuntu 22.04 LTS AMI found in region %s", region)
	}

	// Sort by CreationDate descending to get the most recent image.
	sort.Slice(out.Images, func(i, j int) bool {
		return awssdk.ToString(out.Images[i].CreationDate) > awssdk.ToString(out.Images[j].CreationDate)
	})

	amiID := awssdk.ToString(out.Images[0].ImageId)
	amiName := awssdk.ToString(out.Images[0].Name)
	log.Printf("[INFO] AMI resolution: latest Ubuntu 22.04 in %s is %s (%s)", region, amiID, amiName)
	return amiID, nil
}

// nodeLabelInstanceTypes maps nodeLabel values to their default EC2 instance type.
var nodeLabelInstanceTypes = map[string]string{
	"cpu": "t3.xlarge",
	"gpu": "p3.2xlarge",
}

// DefaultInstanceTypeForLabel returns the recommended EC2 instance type for the
// given nodeLabel.  Returns an empty string when no mapping is defined.
func DefaultInstanceTypeForLabel(nodeLabel string) string {
	return nodeLabelInstanceTypes[strings.ToLower(nodeLabel)]
}

// ValidateInstanceTypeAvailability returns an error if the given instance type
// is not offered in any AZ of the region.  Call this before attempting to launch
// so the NodeProvision phase shows a clear message rather than an AWS error.
func ValidateInstanceTypeAvailability(ctx context.Context, region, instanceType string, creds AWSCredentials) error {
	client, err := newEC2Client(ctx, region, creds)
	if err != nil {
		return fmt.Errorf("creating EC2 client: %w", err)
	}
	out, err := client.DescribeInstanceTypeOfferings(ctx, &ec2.DescribeInstanceTypeOfferingsInput{
		LocationType: types.LocationTypeRegion,
		Filters: []types.Filter{
			{Name: awssdk.String("instance-type"), Values: []string{instanceType}},
			{Name: awssdk.String("location"), Values: []string{region}},
		},
	})
	if err != nil {
		return fmt.Errorf("describing instance type offerings: %w", err)
	}
	if len(out.InstanceTypeOfferings) == 0 {
		return fmt.Errorf("instance type %s is not available in region %s", instanceType, region)
	}
	return nil
}

// ────────────────────────────────────────────────────────────────────────────
// helpers
// ────────────────────────────────────────────────────────────────────────────

const defaultRootVolumeSizeGB = 50

func buildRunInstancesInput(np *mlv1alpha1.NodeProvision, userDataB64 string) *ec2.RunInstancesInput {
	rootVolumeGB := int32(defaultRootVolumeSizeGB)
	if np.Spec.AWSConfig != nil && np.Spec.AWSConfig.RootVolumeSizeGB > 0 {
		rootVolumeGB = np.Spec.AWSConfig.RootVolumeSizeGB
	}

	input := &ec2.RunInstancesInput{
		ImageId:      awssdk.String(np.Spec.AWSConfig.AMI),
		InstanceType: types.InstanceType(np.Spec.InstanceType),
		MinCount:     awssdk.Int32(1),
		MaxCount:     awssdk.Int32(1),
		UserData:     awssdk.String(userDataB64),
		BlockDeviceMappings: []types.BlockDeviceMapping{
			{
				DeviceName: awssdk.String("/dev/sda1"),
				Ebs: &types.EbsBlockDevice{
					VolumeSize:          awssdk.Int32(rootVolumeGB),
					VolumeType:          types.VolumeTypeGp3,
					DeleteOnTermination: awssdk.Bool(true),
				},
			},
		},
		NetworkInterfaces: []types.InstanceNetworkInterfaceSpecification{
			{
				DeviceIndex:              awssdk.Int32(0),
				SubnetId:                 awssdk.String(np.Spec.AWSConfig.SubnetID),
				AssociatePublicIpAddress: awssdk.Bool(true),
			},
		},
		// IMDSv2 only: user-data carries the registry token and VPN private key,
		// so it must not be readable through an SSRF-able IMDSv1 GET. The
		// bootstrap script already uses IMDSv2 tokens. The default hop limit is
		// kept, which also keeps pods from reaching the metadata service.
		MetadataOptions: &types.InstanceMetadataOptionsRequest{
			HttpTokens:   types.HttpTokensStateRequired,
			HttpEndpoint: types.InstanceMetadataEndpointStateEnabled,
		},
	}

	// Tag instance and root volume atomically at launch so the instance can be
	// found by NodeProvision UID even if the controller crashes right after
	// RunInstances, and make the launch idempotent: the same NodeProvision always
	// sends the same ClientToken, so a retried call returns the original
	// instance instead of launching a second one.
	if uid := string(np.UID); uid != "" {
		input.ClientToken = awssdk.String(clientTokenForAttempt(uid, np.Status.ProvisionRetryCount))
		tags := controllerTags(np)
		input.TagSpecifications = []types.TagSpecification{
			{ResourceType: types.ResourceTypeInstance, Tags: tags},
			{ResourceType: types.ResourceTypeVolume, Tags: tags},
		}
	}

	if len(np.Spec.AWSConfig.SecurityGroupIDs) > 0 {
		input.NetworkInterfaces[0].Groups = np.Spec.AWSConfig.SecurityGroupIDs
	}

	if np.Spec.AWSConfig.KeyPairName != "" {
		input.KeyName = awssdk.String(np.Spec.AWSConfig.KeyPairName)
	}

	if np.Spec.AWSConfig.IAMInstanceProfile != "" {
		input.IamInstanceProfile = &types.IamInstanceProfileSpecification{
			Name: awssdk.String(np.Spec.AWSConfig.IAMInstanceProfile),
		}
	}

	return input
}

// maxClientToken is EC2's ClientToken limit (ASCII characters).
const maxClientToken = 64

// clientTokenForAttempt derives the RunInstances ClientToken for one provisioning
// ATTEMPT of a NodeProvision: "np-<uid>-<attempt>", where attempt is
// Status.ProvisionRetryCount. It is deterministic within an attempt (a retried
// call after a crash returns the original instance instead of launching a
// second one) and different for every attempt: after a failed attempt the
// instance is terminated and the relaunch carries new user-data, which with a
// constant token would be rejected with IdempotentParameterMismatch (or return
// the terminated instance). Overlong UIDs are shortened by hashing so the token
// never exceeds 64 characters and the attempt suffix is always preserved.
func clientTokenForAttempt(uid string, attempt int) string {
	if attempt < 0 {
		attempt = 0
	}
	suffix := "-" + strconv.Itoa(attempt)
	base := "np-" + uid
	if len(base)+len(suffix) > maxClientToken {
		sum := sha256.Sum256([]byte(uid))
		base = "np-" + hex.EncodeToString(sum[:])[:maxClientToken-len("np-")-len(suffix)]
	}
	return base + suffix
}

// controllerTags are the tags the controller itself owns; user tags may not
// override them.
func controllerTags(np *mlv1alpha1.NodeProvision) []types.Tag {
	tags := []types.Tag{
		{Key: awssdk.String("Name"), Value: awssdk.String(np.Name)},
		{Key: awssdk.String("managed-by"), Value: awssdk.String("node-provision-controller")},
		{Key: awssdk.String("node-provision-name"), Value: awssdk.String(np.Name)},
		{Key: awssdk.String("node-provision-namespace"), Value: awssdk.String(np.Namespace)},
	}
	if np.UID != "" {
		tags = append(tags, types.Tag{Key: awssdk.String(nodeProvisionUIDTag), Value: awssdk.String(string(np.UID))})
	}
	return tags
}

// sleepCtx waits for d or until ctx is cancelled, whichever comes first.
func sleepCtx(ctx context.Context, d time.Duration) error {
	t := time.NewTimer(d)
	defer t.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-t.C:
		return nil
	}
}

func tagInstance(ctx context.Context, client interface {
	CreateTags(ctx context.Context, params *ec2.CreateTagsInput, optFns ...func(*ec2.Options)) (*ec2.CreateTagsOutput, error)
}, instanceID string, np *mlv1alpha1.NodeProvision) error {
	tags := controllerTags(np)
	reserved := map[string]bool{}
	for _, t := range tags {
		reserved[awssdk.ToString(t.Key)] = true
	}
	if np.Spec.AWSConfig != nil {
		for k, v := range np.Spec.AWSConfig.Tags {
			if reserved[k] {
				continue // controller-owned tag; never let user tags override it
			}
			tags = append(tags, types.Tag{Key: awssdk.String(k), Value: awssdk.String(v)})
		}
	}

	// Retry tagging with backoff because the instance may not yet be visible.
	var lastErr error
	for i := 0; i < 5; i++ {
		_, err := client.CreateTags(ctx, &ec2.CreateTagsInput{
			Resources: []string{instanceID},
			Tags:      tags,
		})
		if err == nil {
			return nil
		}
		lastErr = err
		if werr := sleepCtx(ctx, time.Duration(i+1)*2*time.Second); werr != nil {
			return werr
		}
	}
	return lastErr
}

// parsePort converts a string port value to int, returning defaultPort when
// the string is empty or unparseable. Accepts port fields stored as strings in YAML.
func parsePort(s string, defaultPort int) int {
	if s == "" {
		return defaultPort
	}
	n, err := strconv.Atoi(strings.TrimSpace(s))
	if err != nil || n <= 0 {
		return defaultPort
	}
	return n
}

// FindInstanceIDByNodeProvision returns the ID of a non-terminated EC2
// instance that was launched for this NodeProvision (matched by the
// ml.dcn.ssu.ac.kr/nodeprovision-uid tag), or "" when there is none. It lets
// the controller adopt or clean up an instance whose ID never made it into
// status (crash between RunInstances and the status write).
func FindInstanceIDByNodeProvision(ctx context.Context, nodeProvision *mlv1alpha1.NodeProvision, creds AWSCredentials) (string, error) {
	uid := string(nodeProvision.UID)
	if uid == "" {
		return "", nil
	}
	client, err := newEC2Client(ctx, nodeProvision.Spec.Region, creds)
	if err != nil {
		return "", fmt.Errorf("creating EC2 client: %w", err)
	}
	return findInstanceID(ctx, client, uid)
}

// findInstanceID pages through DescribeInstances for a non-terminated instance
// tagged with uid; when several match the oldest launch wins.
func findInstanceID(ctx context.Context, client ec2DescribeInstancesAPI, uid string) (string, error) {
	if uid == "" {
		return "", nil
	}
	pager := ec2.NewDescribeInstancesPaginator(client, &ec2.DescribeInstancesInput{
		Filters: []types.Filter{
			{Name: awssdk.String("tag:" + nodeProvisionUIDTag), Values: []string{uid}},
			{Name: awssdk.String("instance-state-name"), Values: []string{"pending", "running", "stopping", "stopped"}},
		},
	})
	var (
		bestID   string
		bestTime time.Time
	)
	for pager.HasMorePages() {
		page, err := pager.NextPage(ctx)
		if err != nil {
			return "", fmt.Errorf("describing instances for NodeProvision uid %s: %w", uid, err)
		}
		for _, r := range page.Reservations {
			for _, inst := range r.Instances {
				id := awssdk.ToString(inst.InstanceId)
				if id == "" {
					continue
				}
				if inst.State != nil && (inst.State.Name == types.InstanceStateNameTerminated || inst.State.Name == types.InstanceStateNameShuttingDown) {
					continue // belt and braces: the filter already excludes these
				}
				lt := awssdk.ToTime(inst.LaunchTime)
				if bestID == "" || lt.Before(bestTime) {
					bestID, bestTime = id, lt
				}
			}
		}
	}
	return bestID, nil
}

// ec2DescribeInstancesAPI is the slice of the EC2 client findInstanceID needs
// (an interface so it can be unit-tested with a fake).
type ec2DescribeInstancesAPI interface {
	DescribeInstances(ctx context.Context, params *ec2.DescribeInstancesInput, optFns ...func(*ec2.Options)) (*ec2.DescribeInstancesOutput, error)
}
